name: 🐛 Bug report
description: Describe a problem

body:
  - type: markdown
    attributes:
      value: |
        Some general tips:

        - Is this really a problem?
        - Is this a problem here?
        - Can this be solved in a different way?

  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        - label: I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
          required: true
        - label: I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
          required: true
        - label: I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
          required: true
        - label: I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)
          required: true

  - type: dropdown
    id: javascript-runtime
    attributes:
      label: Runtime
      description: What JavaScript runtime are you using to build or run the code?
      multiple: true
      options:
        - Node v12
        - Node v14
        - Node v16
        - Deno v1
        - Electron v13
        - Electron v12
        - Electron v11
        - Other (please specify in steps to reproduce)
    validations:
      required: false

  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      description: What package manager are you using?
      multiple: true
      options:
        - npm v6
        - npm v7
        - yarn v1
        - yarn v2
        - pnpm
        - Other (please specify in steps to reproduce)
    validations:
      required: false

  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you using?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Other (please specify in steps to reproduce)
    validations:
      required: false

  - type: dropdown
    id: build-tools
    attributes:
      label: Build and bundle tools
      description: What, if any, tools are used to build or bundle the project?
      multiple: true
      options:
        - Webpack
        - Rollup
        - esbuild
        - Parcel
        - Create React App
        - Gatsby
        - Next.js
        - Docusaurus
        - Snowpack
        - Vite
        - Other (please specify in steps to reproduce)
    validations:
      required: false

  - type: input
    id: affected-versions
    attributes:
      label: Affected packages and versions
      description: Please test using the latest version of the relevant packages to make sure your issue has not already been fixed.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead?
    validations:
      required: true

  - type: input
    id: runnable-example
    attributes:
      label: Link to runnable example (optional)
      description: |
        Link to repository or sandbox with runnable example of the issue.
        Some starters for creating a sandbox are provided below: 
        - remark only (for markdown to markdown): https://codesandbox.io/s/remark-debug-ikwvx
        - remark and rehype (for markdown to html): https://codesandbox.io/s/remark-rehype-debug-4cz8v
        - react-markdown: https://codesandbox.io/s/react-markdown-debug-9n4eg
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        How did this happen? Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
        Issues without reproduction steps or code examples may be immediately closed as not actionable.
      placeholder: |
        1.
        2.
        3.

        ...
    validations:
      required: true
