name: 🐛 Bug report
description: Describe a bug with a project
body:
  - type: markdown
    attributes:
      value: |
        Some general tips:

        * Is this really a problem?
        * Is this a problem here?
        * Can this be solved in a different way?
  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        - label: I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
          required: true
        - label: I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
          required: true
        - label: I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
          required: true
        - label: I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)
          required: true
  - type: input
    id: affected-versions
    attributes:
      label: Affected packages and versions
      description: Please test using the latest version of the relevant packages to make sure your issue has not already been fixed.
    validations:
      required: true
  - type: input
    id: runnable-example
    attributes:
      label: Link to runnable example
      description: |
        Link to repository or sandbox with runnable example of the issue.
        Alternatively, use the next section *Steps to reproduce*.

        Some starters:

        | description | codesandbox | stackblitz |
        | - | - | - |
        | remark only (for markdown to markdown) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-parcel) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-parcel) |
        | remark and rehype (for markdown to html) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-parcel) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-parcel) |
        | react-markdown | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-create-react-app) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-create-react-app) |
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How did this happen? Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead?
    validations:
      required: true
  - type: input
    id: runtime
    attributes:
      label: Affected runtime and version
      description: |
        What runtime are you using (e.g., `node@18.2`, `deno@1.12.2`)?
        Please test using the latest version.
    validations:
      required: true
  - type: input
    id: package-manager
    attributes:
      label: Affected package manager and version
      description: |
        What package manager are you using (e.g., `npm@8.9.0`)?
        Please test using the latest version.
    validations:
      required: false
  - type: input
    id: operating-system
    attributes:
      label: Affected OS and version
      description: |
        What operating system are you using (e.g., `macOS Monterey 12.4`)?
        Please test using the latest version.
    validations:
      required: false
  - type: dropdown
    id: build-tools
    attributes:
      label: Build and bundle tools
      description: |
        What, if any, tools are used to build or bundle the project?
        Please test using the latest version.
      multiple: true
      options:
        - webpack
        - Rollup
        - esbuild
        - swc
        - Parcel
        - CRA (Create React App)
        - Vite
        - Next.js
        - Remix
        - Astro
        - Docusaurus
        - Gatsby
        - Other (please specify in steps to reproduce)
    validations:
      required: false
